version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitnest-backend
    restart: always
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - fitnest-network
    volumes:
      - backend-data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitnest-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fitnest-network

networks:
  fitnest-network:
    driver: bridge

volumes:
  backend-data:
