version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fit-nest-backend
    restart: unless-stopped    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add other environment variables as needed
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - fit-nest-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: fit-nest-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - fit-nest-network

networks:
  fit-nest-network:
    driver: bridge
